[package]
name = "primeless_year"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rug = "1.14.0"
rand = "0.8.4"

[dev-dependencies]
rstest = "0.12.0"
chrono = "0.4.19"